### ISSUE TITLE
last try pls

### ISSUE THREAD

**Issue by jaydenkieran** [jaydenkieran/Test#3]
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 997, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 924, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 976, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Stephen\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError('qC',))

???? Pls explain? and with fix please!

**Comment by jaydenkieran** [comment]
> This is an auto-response generated based on the content of your issue. If this does not solve your issue, please comment on this issue requesting for it to be re-opened.

This is a `youtube_dl` bug (https://github.com/rg3/youtube-dl/issues/11663) and is fixed. You need to update ytdl using our dependency update scripts:

- Windows: Open `update_deps.bat`
- Linux: Run `python3.5 -m pip install --upgrade -r requirements.txt`
- Mac: Open `update_macdeps.command` in Terminal

You can also update ytdl manually using the command `sudo pip install -U youtube-dl`.
